# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 32
#$ -q mThC.q
#$ -l mres=256G,h_data=8G,h_vmem=6G
#$ -cwd
#$ -j y
#$ -N cStacks
#$ -o cStacks.log
#
# ----------------Modules------------------------- #
module load bioinformatics/stacks/2.66
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
cstacks \
	-n 6 \
	-p "${NSLOTS}" \
	-P /Path/to/stacks/working/directory \
	-M /Path/to/stacks/sample/population/file/popmap.txt 
#
echo = `date` job $JOB_NAME done